/* Generated by Together */

#ifndef IMVDSpannedFiles_H
#define IMVDSpannedFiles_H


/**
 * This is the common interface for AV file reading operation.
 * From the AVI Filke info , we should be able to know the file is progressive or interlaced.
 * @interface
 */
interface IMvdSpannedFiles : public IUnknown
{
public:

   /** Here we set the file name */
   virtual HRESULT __stdcall SetFileName( LPCWSTR in_pcwszFileName ) = 0;

   virtual uint32_t __stdcall GetSpannedFilesCount( ) = 0;

   virtual HRESULT __stdcall GetSpannedFileAt(uint32_t in_idxFile, wchar_t * out_pwcFileName ) = 0; 


};
#endif //IMVDSpannedFiles_H




